### ISSUE TITLE
Site build fails repeatedly : (

### ISSUE THREAD

**Issue by itsN1X** [MozillaTN/VIT#1]
@hellokarthic @
Normally I would set the gh-pages to build from the ~master branch of my rep under the settings tab. Since I'm not (yet) a member (still coord) to the MozillaTN org, I dont have enough priv. to get that done on my own.
help! 

p.s. - see [ @vMozilla || @itsN1X ] / [ MozillaTN-VIT ](http://itsn1x.github.io/MozillaTN-VIT)

**Comment by iamVP7** [comment]
I don't see any message related to build failure. And we are using Jekyll so we used docs folder no need to use gh-pages. I have enabled Website temporarily.

PS:- it's not required to be member in @MozillaTN account just you have to be admin for the repo.
Cc @hellokarthic

**Comment by itsN1X** [comment]
So what's the cause for not getting it online? @iamVP7 
Ref above links.

**Comment by iamVP7** [comment]
https://mozillatn.github.io/VIT/ it's working for me.. u didn't do any changes to config.yml and other places u have to, so ur not seeing the changes

**Comment by itsN1X** [comment]
Temporarily? Will it go down again somehow? What was the problem with the earlier one? 
Thanks : D

###### edit:
$`i` :`was looking at my local fork prior plush`
